### ISSUE TITLE
C4Socket static hashmap entries

### ISSUE THREAD

**Issue by dtchepak** [couchbase/couchbase-lite-android-ce#25] opened 2019-09-13 07:07 UTC
Hi!

I've been doing some profiling to try to find out what's keeping some instances alive. I think I've tracked down one culprit: I can find where `C4Socket` [static hashmap](https://github.com/couchbase/couchbase-lite-java/blob/c6533303189d5db7a88fa18d18f9605a8fa23062/src/shared/main/java/com/couchbase/lite/internal/core/C4Socket.java#L102) entries get added, but not where they get removed. This is fairly new to me on this platform so my apologies if I have this wrong, but thought I'd raise it in case it was helpful.

[`C4Socket.java`:](https://github.com/couchbase/couchbase-lite-java/blob/c6533303189d5db7a88fa18d18f9605a8fa23062/src/shared/main/java/com/couchbase/lite/internal/core/C4Socket.java#L102) 
```
    // Map between SocketFactory Context and SocketFactory Class
    public static final Map<Object, Class> SOCKET_FACTORY
        = Collections.synchronizedMap(new HashMap<>());

    // Map between SocketFactory Context and Replicator
    public static final Map<Object, Replicator> SOCKET_FACTORY_CONTEXT
        = Collections.synchronizedMap(new HashMap<>());
```

[`AbstractReplicator.java`:](
https://github.com/couchbase/couchbase-lite-java/blob/c6533303189d5db7a88fa18d18f9605a8fa23062/src/shared/main/java/com/couchbase/lite/AbstractReplicator.java#L744)
```
C4Socket.SOCKET_FACTORY_CONTEXT.put(this, (Replicator) this);
```

[`Replicator.java`:](
https://github.com/couchbase/couchbase-lite-java/blob/c6533303189d5db7a88fa18d18f9605a8fa23062/src/shared/ce/java/com/couchbase/lite/Replicator.java#L21)
```
    void initSocketFactory(Object socketFactoryContext) {
        C4Socket.SOCKET_FACTORY.put(socketFactoryContext, CBLWebSocket.class);
    }
```

Is there a way to remove these references once no longer needed? Or replace with `WeakReference`s?

I started looking into this because I could not tell what was referencing an instance I have. Profiling indicated the `Replicator` keeps alive the `ReplicatorConfiguration` which keeps alive the push filter which closes over some variables from that instance.

**Comment by bmeike** [comment] 2019-09-14 01:02
What version of CB-Lite are you using?

**Comment by dtchepak** [comment] 2019-09-14 03:48
@bmeike 2.6.0

**Comment by dtchepak** [comment] 2019-09-14 06:51
Can reproduce the symptom with an app that triggers one-time replication on button press. Profiling app, triggering a few replications, forcing GC using profiler, then doing a heap dump in profiler should show multiple `Replicator` objects still live.

**Comment by bmeike** [comment] 2019-09-15 17:57
What is it that is staying "alive" that you believe should not be?  You say "instances"?  Instances of what?
Those two maps that you cite are essential for keeping references to objects used by replicators.

**Comment by dtchepak** [comment] 2019-09-15 23:26
Hi @bmeike, 
Thanks for your reply.

The instances are of type `Replicator` (which in turn keeps a `ReplicatorConfiguration` instance, which keeps a `Database` instance and any push/pull filters). These are kept after the replicator status reaches `STOPPED` state, and after forcing GC. This is for one-shot replicator configurations (not continuous).

Are `Replicator` instances meant to be reused from client code? Due to the readonly config I'm creating a new one each time as I sometimes need to update the auth token used. If this is incorrect please let me know!

I will try to get a reproduction pushed up for you to take a look at. As far as I can tell `Replicator` instances and associated info will never get garbage collected for the life of the application. I may be mistaken about this, but I think it's worth checking to make sure these things can be cleaned up once no longer necessary. 😄

**Comment by dtchepak** [comment] 2019-09-16 04:35
I've attempted to add a repro case here: https://github.com/dtchepak/android-workshop/tree/acd5551e7892b42d2d05938273280df0dc559f99.

Steps:

* Start app and begin profiling.
* Tap "CBL Example" button.
* Navigate back without starting replication.
* In profiler, force GC then do a heap dump. Observe that heap does not contain any CBL `Database` or `Replicator` objects.
* Tap "CBL Example" button.
* Enter syncgateway details and start replication, and wait for it to stop again as indicated by status (it does not matter if you don't put in valid replication details, just attempting to hit the end point is sufficient).
* Do the replication a total of `x` times.
* Navigate back to main activity. All CBL objects should now be eligible for GC.
* In profiler, force GC then do a heap dump. Observe that heap contains `x` number of `Replicator` instances, and also a `Database` instance that is kept alive by the `Replicator` instance. Compare to earlier step where `Database` instances were cleaned up properly after exiting the activity without starting a `Replicator`.

Example of running 7 replications (and allowing to stop):

![Profiler showing Replicator instances and the references keeping them alive](https://user-images.githubusercontent.com/70105/64934528-cabf4880-d88e-11e9-8bc0-b188c827ae91.png)

Please let me know if you need more info.

**Comment by bmeike** [comment] 2019-09-16 16:59
> The instances are of type Replicator (which in turn keeps a ReplicatorConfiguration instance, which keeps a Database instance and any push/pull filters). These are kept after the replicator status reaches STOPPED state, and after forcing GC. This is for one-shot replicator configurations (not continuous).

> Are Replicator instances meant to be reused from client code? Due to the readonly config I'm creating a new one each time as I sometimes need to update the auth token used. If this is incorrect please let me know!

Yes.  Exactly.  This is not a bug.  Until the Replicator reaches a stopped state, it, its configuration, and the Database to which it refers *must* be kept available.  They can be invoked, asynchronously, at any time (until the replicator is stopped) by the native code.  This is not a leak.  This is correct behavior.

**Comment by bmeike** [comment] 2019-09-16 19:03
You are correct.  This is a pretty horrible leak.  Thanks for pointing it out.

Tracking in https://issues.couchbase.com/browse/CBL-404

**Comment by bmeike** [comment] 2019-09-27 01:23
This bug has been fixed.  Code is in the master branch.  Closing.

**Closed by bmeike** 2019-09-27 01:23 UTC
Labels: bug, triaged

**Comment by dtchepak** [comment] 2019-09-27 01:51
@bmeike Thanks! The change looks awesome 👍 

Do you have any idea of when this will be in a release? (weeks, months?)

**Comment by bmeike** [comment] 2019-09-30 16:42
Not my baliwick.  I'd bet more like months...
